fix(lsp): missing `source` parameter (#1451)
* fix(lsp): missing `source` parameter

Error: "failed to execute item with error: ...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lsp/init.lua:186: attempt to index global 'source' (a nil value)"

* refactor: rename `source` to `ctx` in lsp source

---------

Co-authored-by: Liam Dyer <liamcdyer@gmail.com>