fix(lsp): missing `source` parameter
Error: "failed to execute item with error: ...e/nvim/lazy/blink.cmp/lua/blink/cmp/sources/lsp/init.lua:186: attempt to index global 'source' (a nil value)"